//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLD521_SA.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public int PapersID { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public Nullable<System.DateTime> Date_Submitted { get; set; }
        public string Topic { get; set; }
    }
}
